### ISSUE TITLE
Can't run; control characters are not allowed

### ISSUE THREAD

**Issue by XtracT** [nebhale/teslamate-discovery#111]
Hello!

I am trying to run teslamate-discovery, but I am raunning into what could be a very newbie issue:

```
$ ./teslamate-discovery -h "127.0.0.1" -u "user" -P "pass"
Error: While parsing config: yaml: control characters are not allowed
Usage:
  teslamate-discovery [flags]

Flags:
      --ha-discovery-prefix string   home assistant discovery message prefix (default "homeassistant")
      --help                         help for teslamate-discovery
  -h, --mqtt-host string             mqtt broker host (default "127.0.0.1")
  -P, --mqtt-password string         mqtt broker password
  -p, --mqtt-port int                mqtt broker port (default 8883)
  -s, --mqtt-scheme string           mqtt broker scheme (default "ssl")
  -u, --mqtt-username string         mqtt broker username
      --range-type string            range type ["estimated", "ideal", "rated"] (default "rated")
      --tm-prefix string             teslamate message prefix (default "teslamate")
      --units-distance string        distance units ["imperial", "metric"] (default "imperial")
      --units-pressure string        pressure units ["imperial", "metric"] (default "imperial")
  -v, --version                      version for teslamate-discovery

```
No matter what I write in the cli I always seem to get this go-yaml error. Any hints at why? I have tried in three different machines (2 arm 1 amd64) with the same result. Also downloaded the previous version and the same. Any hints?

Thanks for your time!

/Xtract

**Comment by nebhale** [comment]
OK, so the only place I think we ever YAML is reading a config file when you start up.  Can you please check to see if you've got a `teslamate-discovery` config file/directory in either 

* `$HOME/.config/` (Linux)
* `$HOME/Library/Application Support` (macOS)

**Comment by XtracT** [comment]
Hello,

No, I do not have anything of the sorts, and the binary does not seem to have created them or anything. I have just tried making a small docker container with the binary, and it fails as well:

```
FROM alpine:latest
WORKDIR /app
COPY teslamate-discovery /app/teslamate-discovery
CMD [ "/app/teslamate-discovery" ]
```

Well, even running the command without any arguments returns the same yaml error. With `--help` it does not do it.

**Comment by nebhale** [comment]
Good news: reproduced.  Working on it now.

**Comment by nebhale** [comment]
I've managed to reproduce the error and will let you know when I've got a fix.

**Comment by nebhale** [comment]
OK, so the root of the problem was that the application would attempt to optionally read its configuration from the filesystem from a handful of locations, and the expected configuration file's name would be `teslamate-discovery`.  This would work fine so long as the binary you were running wasn't in either `$HOME` or `.`, and in my testing, I never have it in either.  In that `Dockerfile`, I believe it lands in both of those causing the issue.  PR coming through in a minute that changes what that file is named and where it can be located.

Thank you so much for the report and the reproduction steps!

**Comment by XtracT** [comment]
Many thanks, it works now!
