### ISSUE TITLE
unauthenticated MQTT server

### ISSUE THREAD

**Issue by joseftsch** [nebhale/teslamate-discovery#129]
Hey, 
My internal MQTT server does not have any kind of authentication.
Do you think you could make your tool work with anonymous MQTT?

thanks

**Comment by joseftsch** [comment]
Apparently specifying a not existing user/pw and schema "mqtt" did work :)
`./teslamate-discovery -h 192.168.1.142 --units-distance metric --units-pressure metric -P test -u test -p 1883 -s mqtt
`

**Comment by nebhale** [comment]
Good to hear that that worked for you!
