### ISSUE TITLE
device.Name not populated

### ISSUE THREAD

**Issue by mekaneck** [nebhale/teslamate-discovery#44]
I don't know the GO language, but when I run the script the `device.Name` variable is empty and as a result, all the sensor names don't have a prefix and therefore all start with a leading space and then the sensor suffix, for example after running the script I see in Home Assistant:
Sensor Name = ` Speed` (note the leading space)
entity_id = `sensor.speed`

The location sensor also doesn't work correctly due to this issue, because its longitude attribute incorrectly looks for an entity_id of `sensor._longitude`

If I could figure out how to populate the device.Name I believe it would work flawlessly.

https://github.com/nebhale/teslamate-discovery/blob/754d964998e9e4a9dc279e3f2be69ee4cf37c502/ha/device.go#L10

Below is the line that is returning sensor names with a leading space, but note that there's nothing wrong with this code, the issue is that `device.Name` is empty when the line of code is executed.
https://github.com/nebhale/teslamate-discovery/blob/754d964998e9e4a9dc279e3f2be69ee4cf37c502/mqtt/publish_discovery.go#L404

**Comment by mekaneck** [comment]
I am not using this software any more, but I did come to the conclusion that I never named my car (via the touchscreen inside the car itself), and this is likely why `device.Name` was not populated. It would be nice if there were a default for this code to revert back to in a scenario like this. Something as simple as "tesla" would suffice.

**Comment by nebhale** [comment]
Your diagnosis does match my investigation into the code.  Your suggestion of a default makes sense as well.  I'll add that and thanks for the pointer to the invalid assumption.
