### ISSUE TITLE
Device and entities created in HA but all remain as Unknown 

### ISSUE THREAD

**Issue by abreingan** [nebhale/teslamate-discovery#72]
Hi and my apologies for probably the worst sort of newbie question. 
I have a mosquito MQTT addon running in HA, and TeslaMate installed and running, and showing up to date information.
I created the access control list as described, and ran  teslamate-discovery, which created the Device and a long list of entities. 
However the entities are all showing as Unknown, and I don't understand how / where the link between the created entity and the  Teslamate MQTT message is defined. 
Any help would be wonderful, thanks 
Al

**Comment by nebhale** [comment]
The tool is built on top of the [MQTT Discovery System](https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery) in Home Assistant.  Reading the docs, it's a bit opaque as to how this works, but roughly, there's a "persistent" message on a special MQTT topic that says "for a thing called this, use the value in this other topic".

An example:

<img width="689" alt="image" src="https://github.com/nebhale/teslamate-discovery/assets/60754/c97d433c-894e-42bb-b1b1-068393887335">

At `homeassistant/binary_sensor/teslamate_pbsurveyor_cars_1/windows/config` there's a retained payload that says "go look at `teslamate/pbsurveyor/cars/1/windows_open` for the state of this entity.  You should be able to go to that topic and find a state for it:

<img width="481" alt="image" src="https://github.com/nebhale/teslamate-discovery/assets/60754/b2b7e0ff-cbfc-4280-9267-ae53be480e24">

---
So, for troubleshooting my first port of call would be to get an MQTT browser (e.g. [MQTTX](https://mqttx.app), [MQTT Explorer](https://mqtt-explorer.com)) and verify that you've both got a config that points to a reasonable topic and that the topic has some data within it.

**Comment by abreingan** [comment]
Thank you very much nebhale, that got me over the line. 
In case it is of use to anyone else my issue was that Teslamate was publishing on teslamate/teslamate/cars/1/# (why I don't know - I could not see an option I might have misconfigured). 
Running teslamate-discovery without the --tm-prefix resulted in discovery messages looking for teslamate/cars/1/# and obviously not finding them.
Running teslamate-discovery with --tm-prefix teslamate/teslamate fixed things and all is well.
Thanks again for your help and the excellent tool - very elegant

**Comment by nebhale** [comment]
Glad that helped!  I'm not sure exactly how you're running Teslamate, but you might take a look to see if `$MQTT_NAMESPACE` (`mqtt_namespace` with the [Home Assistant Addon](https://github.com/matt-FFFFFF/hassio-addon-teslamate/tree/main)) is set.  I'd bet it's set somewhere to `teslamate` which is inserting the extra path segment.

**Comment by abreingan** [comment]
Yes that was exactly my problem. I was running the home assistant add-on and had set the mqtt_namespace to teslamate. blanking that out restores MQTT message on teslamate/cars/1/#
Thanks again
Very minor comment that running with --units-distance metric --units-pressure imperial (I know its a bit twisted) seems to use metric for pressure as well as distance.

**Comment by nebhale** [comment]
This is definitely a bug.  I’ve opened #74 for it.
